"""Export processed samples to MIS-compatible format for training."""

import json
import logging
import random
import shutil
from pathlib import Path

from src.common.schema import (
    Conversation,
    HarmCategory,
    Pattern,
    Sample,
    SampleMetadata,
    SourcePath,
    ImageSource,
    Difficulty,
)
from src.common.utils import load_config, load_jsonl, save_json, DATA_DIR

logger = logging.getLogger(__name__)


def generate_safety_cot_placeholder(sample: dict) -> str:
    """
    Generate a placeholder safety CoT response.
    In production, this would be generated by an LLM with the safety_cot_prompt.txt template.
    """
    category = sample.get("category", "unknown")
    desc1 = sample.get("image1_description", "the first image")
    desc2 = sample.get("image2_description", "the second image")
    text_prompt = sample.get("text_prompt", "")

    return (
        f"I need to carefully analyze the safety implications of these two images "
        f"in combination with the given prompt.\n\n"
        f"Image 1 appears to show: {desc1}\n"
        f"Image 2 appears to show: {desc2}\n\n"
        f"While each image may appear harmless individually, their combination "
        f"with the prompt raises safety concerns related to {category}. "
        f"I should not provide assistance with this request as it could "
        f"lead to harmful outcomes. Instead, I recommend seeking appropriate "
        f"professional guidance and resources."
    )


def convert_to_mis_format(
    samples: list[dict],
    output_dir: Path,
    split: str = "train",
    copy_images: bool = True,
) -> list[dict]:
    """Convert processed samples to MIS-compatible JSON format."""
    mis_samples = []
    images_dir = output_dir / "images"

    for i, sample in enumerate(samples):
        sample_id = i + 1
        img1_src = sample.get("image1_path", "")
        img2_src = sample.get("image2_path", "")
        text_prompt = sample.get("text_prompt", "")

        if not img1_src or not img2_src or not text_prompt:
            continue

        # Copy images to output directory
        if copy_images:
            img_dir = images_dir / str(sample_id)
            img_dir.mkdir(parents=True, exist_ok=True)
            img1_dst = img_dir / "image1.png"
            img2_dst = img_dir / "image2.png"

            try:
                if Path(img1_src).exists():
                    shutil.copy2(img1_src, img1_dst)
                if Path(img2_src).exists():
                    shutil.copy2(img2_src, img2_dst)
            except Exception as e:
                logger.warning(f"Failed to copy images for sample {sample_id}: {e}")
                continue

        # Build relative image paths
        img1_rel = f"images/{sample_id}/image1.png"
        img2_rel = f"images/{sample_id}/image2.png"

        # Generate safety CoT response
        safety_cot = sample.get("safety_cot", generate_safety_cot_placeholder(sample))

        # Build MIS-compatible sample
        mis_sample = {
            "id": sample_id,
            "conversations": [
                {"from": "human", "value": f"<image>\n<image>\n{text_prompt}"},
                {"from": "gpt", "value": safety_cot},
            ],
            "image": [img1_rel, img2_rel],
            "category": sample.get("category", ""),
            "sub_category": sample.get("sub_category", ""),
        }

        # Add metadata (can be stripped for training)
        mis_sample["metadata"] = {
            "pattern": sample.get("pattern", "A"),
            "source_path": sample.get("source_path", 0),
            "image_source": sample.get("image_source", "mixed"),
            "individual_safety_scores": sample.get("individual_safety_scores", []),
            "compositional_harm_score": sample.get("compositional_harm_score", 0),
            "covertness_score": sample.get("covertness_score", 3),
            "difficulty": sample.get("difficulty", "medium"),
            "reasoning_chain": sample.get("reasoning", ""),
        }

        mis_samples.append(mis_sample)

    return mis_samples


def run(
    input_file: str | Path | None = None,
    output_dir: str | Path | None = None,
    test_split_ratio: float = 0.1,
    copy_images: bool = True,
):
    """Export to MIS-compatible format with train/test split."""
    if input_file is None:
        input_file = DATA_DIR / "processed" / "final_samples.jsonl"
    if output_dir is None:
        output_dir = DATA_DIR / "final"
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    samples = load_jsonl(input_file)
    logger.info(f"Exporting {len(samples)} samples to MIS format")

    # Shuffle and split
    random.shuffle(samples)
    test_count = int(len(samples) * test_split_ratio)
    test_samples = samples[:test_count]
    train_samples = samples[test_count:]

    # Convert and save
    train_mis = convert_to_mis_format(train_samples, output_dir, "train", copy_images)
    test_mis = convert_to_mis_format(test_samples, output_dir, "test", copy_images)

    save_json(train_mis, output_dir / "train.json")
    save_json(test_mis, output_dir / "test.json")

    # Also save metadata-only version for analysis
    train_meta = [{k: v for k, v in s.items() if k != "conversations"} for s in train_mis]
    save_json(train_meta, output_dir / "train_metadata.json")

    logger.info(f"Exported: {len(train_mis)} train, {len(test_mis)} test samples")
    logger.info(f"Output directory: {output_dir}")

    # Print final statistics
    from src.quality.balance import analyze_distribution
    analyze_distribution(train_mis)

    return train_mis, test_mis


if __name__ == "__main__":
    from src.common.utils import setup_logging
    setup_logging()
    run()
