#!/bin/bash
set -euo pipefail

PROJECT_ROOT="/mnt/hdd/xuran/multi_image_safety"
LOG_DIR="$PROJECT_ROOT/logs"
TIMESTAMP="$(date '+%Y%m%d_%H%M%S')"
LOG_FILE="$LOG_DIR/path1_${TIMESTAMP}.log"

mkdir -p "$LOG_DIR"

# Load optional local secrets such as Pexels / Pixabay API keys.
# shellcheck disable=SC1091
source "$PROJECT_ROOT/scripts/_load_local_env.sh"

export HF_HOME="${HF_HOME:-/mnt2/xuran_hdd/cache}"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
export VLLM_ENABLE_V1_MULTIPROCESSING="${VLLM_ENABLE_V1_MULTIPROCESSING:-0}"
export VLLM_WORKER_MULTIPROC_METHOD="${VLLM_WORKER_MULTIPROC_METHOD:-spawn}"
export MIS_PATH1_MAX_MODEL_LEN="${MIS_PATH1_MAX_MODEL_LEN:-4096}"
export MIS_PATH1_GPU_MEMORY_UTILIZATION="${MIS_PATH1_GPU_MEMORY_UTILIZATION:-0.68}"
export PYTHONPATH="$PROJECT_ROOT${PYTHONPATH:+:$PYTHONPATH}"

export MIS_RETRIEVAL_QUERY_MODE=adaptive
export MIS_RETRIEVAL_QUERY_VARIANTS=4
export MIS_RETRIEVAL_MAX_QUERY_WORDS=2
export MIS_RETRIEVAL_CLIP_TOP_K=5
export MIS_RETRIEVAL_CLIP_KEEP=1
export MIS_RETRIEVAL_CLIP_MIN_SCORE_LOCAL=0.22
export MIS_RETRIEVAL_CLIP_MIN_SCORE_WEB=0.24
export MIS_LOCAL_SEARCH_MODE="${MIS_LOCAL_SEARCH_MODE:-fast}"
export MIS_LOCAL_SEARCH_EARLY_STOP_AT="${MIS_LOCAL_SEARCH_EARLY_STOP_AT:-4}"
export MIS_LOCAL_SEARCH_TARGET_CANDIDATES="${MIS_LOCAL_SEARCH_TARGET_CANDIDATES:-4}"
export MIS_RECAP_QUERY_LIMIT="${MIS_RECAP_QUERY_LIMIT:-24}"
export MIS_SINGLE_IMAGE_LOCAL_CANDIDATES="${MIS_SINGLE_IMAGE_LOCAL_CANDIDATES:-4}"
export MIS_RETRIEVAL_WORKERS_PER_GPU="${MIS_RETRIEVAL_WORKERS_PER_GPU:-8}"
export MIS_PATH5_CRAWL_WORKERS="${MIS_PATH5_CRAWL_WORKERS:-12}"
export MIS_PATH1_ALLOW_IMAGE_GENERATION=1

# ── 是否清除 step 完成标记，重新增量运行 ──────────────────────────────────────
# 修改这里：1 = 清除标记（增量重跑所有步骤），0 = 跳过已完成步骤
CLEAN=0

# 也可以在命令行传 --clean 覆盖此设置
for arg in "$@"; do
  [[ "$arg" == "--clean" ]] && CLEAN=1
done

echo "Running Path 1: KG Concept Pair Mining"
echo "CUDA_VISIBLE_DEVICES: ${CUDA_VISIBLE_DEVICES:-<not set>}"
echo "MIS_GPU_CANDIDATES: ${MIS_GPU_CANDIDATES:-<not set>}"
echo "MIS_PATH1_ALLOW_IMAGE_GENERATION: ${MIS_PATH1_ALLOW_IMAGE_GENERATION}"
echo "MIS_RETRIEVAL_MAX_QUERY_WORDS: ${MIS_RETRIEVAL_MAX_QUERY_WORDS}"
echo "MIS_LOCAL_SEARCH_MODE: ${MIS_LOCAL_SEARCH_MODE}"
echo "MIS_LOCAL_SEARCH_EARLY_STOP_AT: ${MIS_LOCAL_SEARCH_EARLY_STOP_AT}"
echo "MIS_SINGLE_IMAGE_LOCAL_CANDIDATES: ${MIS_SINGLE_IMAGE_LOCAL_CANDIDATES}"
echo "MIS_RECAP_QUERY_LIMIT: ${MIS_RECAP_QUERY_LIMIT}"
echo "MIS_RETRIEVAL_WORKERS_PER_GPU: ${MIS_RETRIEVAL_WORKERS_PER_GPU}"
echo "MIS_PATH5_CRAWL_WORKERS: ${MIS_PATH5_CRAWL_WORKERS}"
echo "PEXELS_API_KEY: ${PEXELS_API_KEY:+<set>}"
echo "PIXABAY_API_KEY: ${PIXABAY_API_KEY:+<set>}"
echo "Log file: ${LOG_FILE}"

clean_flag=()
[[ "$CLEAN" == "1" ]] && clean_flag=("--clean")

python "$PROJECT_ROOT/run_path1.py" "${clean_flag[@]}" 2>&1 | tee "$LOG_FILE"
