#!/bin/bash
set -euo pipefail

PROJECT_ROOT="/mnt/hdd/xuran/multi_image_safety"
LOG_DIR="$PROJECT_ROOT/logs"
TIMESTAMP="$(date '+%Y%m%d_%H%M%S')"
LOG_FILE="$LOG_DIR/path5_${TIMESTAMP}.log"

mkdir -p "$LOG_DIR"

# shellcheck disable=SC1091
source "$PROJECT_ROOT/scripts/_load_local_env.sh"

export HF_HOME="${HF_HOME:-/mnt2/xuran_hdd/cache}"
export PYTHONPATH="$PROJECT_ROOT${PYTHONPATH:+:$PYTHONPATH}"
export MIS_RETRIEVAL_QUERY_MODE=adaptive
export MIS_RETRIEVAL_QUERY_VARIANTS=4
export MIS_RETRIEVAL_MAX_QUERY_WORDS="${MIS_RETRIEVAL_MAX_QUERY_WORDS:-3}"
export MIS_RETRIEVAL_CLIP_TOP_K="${MIS_RETRIEVAL_CLIP_TOP_K:-8}"
export MIS_RETRIEVAL_CLIP_KEEP="${MIS_RETRIEVAL_CLIP_KEEP:-2}"
export MIS_RETRIEVAL_CLIP_MIN_SCORE_LOCAL="${MIS_RETRIEVAL_CLIP_MIN_SCORE_LOCAL:-0.20}"
export MIS_RETRIEVAL_CLIP_MIN_SCORE_WEB="${MIS_RETRIEVAL_CLIP_MIN_SCORE_WEB:-0.22}"
export MIS_LOCAL_SEARCH_MODE="${MIS_LOCAL_SEARCH_MODE:-thorough}"
export MIS_LOCAL_SOURCE_MIX="${MIS_LOCAL_SOURCE_MIX:-1}"
export MIS_LOCAL_SEARCH_EARLY_STOP_AT="${MIS_LOCAL_SEARCH_EARLY_STOP_AT:-8}"
export MIS_LOCAL_SEARCH_TARGET_CANDIDATES="${MIS_LOCAL_SEARCH_TARGET_CANDIDATES:-8}"
export MIS_RECAP_QUERY_LIMIT="${MIS_RECAP_QUERY_LIMIT:-64}"
export MIS_PATH5_LOCAL_CANDIDATES="${MIS_PATH5_LOCAL_CANDIDATES:-10}"
export MIS_PATH5_SKIP_LOCAL_DATASETS="${MIS_PATH5_SKIP_LOCAL_DATASETS:-0}"
export MIS_RETRIEVAL_ALLOW_COMPACT_REWRITE="${MIS_RETRIEVAL_ALLOW_COMPACT_REWRITE:-1}"
export MIS_PATH5_MIN_IMAGES="${MIS_PATH5_MIN_IMAGES:-2600}"
export MIS_PATH5_MAX_IMAGES_PER_CATEGORY="${MIS_PATH5_MAX_IMAGES_PER_CATEGORY:-1800}"
export MIS_PATH5_T2I_MAX_PER_CATEGORY="${MIS_PATH5_T2I_MAX_PER_CATEGORY:-260}"
export MIS_PATH5_MAX_CANDIDATE_PAIRS="${MIS_PATH5_MAX_CANDIDATE_PAIRS:-60000}"
export MIS_PATH5_MAX_INTRA_PER_CATEGORY="${MIS_PATH5_MAX_INTRA_PER_CATEGORY:-2400}"
export MIS_PATH5_MAX_CROSS_PER_COMBO="${MIS_PATH5_MAX_CROSS_PER_COMBO:-1800}"
export MIS_PATH5_MAX_CROSS_SOURCE_PER_CATEGORY="${MIS_PATH5_MAX_CROSS_SOURCE_PER_CATEGORY:-2200}"
export MIS_PATH5_MAX_UNCATEGORIZED_MIX="${MIS_PATH5_MAX_UNCATEGORIZED_MIX:-2400}"
export MIS_RETRIEVAL_WORKERS_PER_GPU="${MIS_RETRIEVAL_WORKERS_PER_GPU:-20}"
export MIS_PATH5_CRAWL_WORKERS="${MIS_PATH5_CRAWL_WORKERS:-20}"
export MIS_PATH5_ALLOW_IMAGE_GENERATION=1

# ── 是否清除 step 完成标记，重新增量运行 ──────────────────────────────────────
# 修改这里：1 = 清除标记（增量重跑所有步骤），0 = 跳过已完成步骤
CLEAN=0

# 也可以在命令行传 --clean 覆盖此设置
for arg in "$@"; do
  [[ "$arg" == "--clean" ]] && CLEAN=1
done

echo "Running Path 5: Embedding Pair Matching"
echo "CUDA_VISIBLE_DEVICES: ${CUDA_VISIBLE_DEVICES:-<not set>}"
echo "MIS_GPU_CANDIDATES: ${MIS_GPU_CANDIDATES:-<not set>}"
echo "MIS_PATH5_ALLOW_IMAGE_GENERATION: ${MIS_PATH5_ALLOW_IMAGE_GENERATION}"
echo "MIS_RETRIEVAL_MAX_QUERY_WORDS: ${MIS_RETRIEVAL_MAX_QUERY_WORDS}"
echo "MIS_LOCAL_SEARCH_MODE: ${MIS_LOCAL_SEARCH_MODE}"
echo "MIS_LOCAL_SOURCE_MIX: ${MIS_LOCAL_SOURCE_MIX}"
echo "MIS_LOCAL_SEARCH_EARLY_STOP_AT: ${MIS_LOCAL_SEARCH_EARLY_STOP_AT}"
echo "MIS_PATH5_LOCAL_CANDIDATES: ${MIS_PATH5_LOCAL_CANDIDATES}"
echo "MIS_PATH5_SKIP_LOCAL_DATASETS: ${MIS_PATH5_SKIP_LOCAL_DATASETS}"
echo "MIS_RECAP_QUERY_LIMIT: ${MIS_RECAP_QUERY_LIMIT}"
echo "MIS_RETRIEVAL_ALLOW_COMPACT_REWRITE: ${MIS_RETRIEVAL_ALLOW_COMPACT_REWRITE}"
echo "MIS_PATH5_MIN_IMAGES: ${MIS_PATH5_MIN_IMAGES}"
echo "MIS_PATH5_MAX_IMAGES_PER_CATEGORY: ${MIS_PATH5_MAX_IMAGES_PER_CATEGORY}"
echo "MIS_PATH5_T2I_MAX_PER_CATEGORY: ${MIS_PATH5_T2I_MAX_PER_CATEGORY}"
echo "MIS_PATH5_MAX_CANDIDATE_PAIRS: ${MIS_PATH5_MAX_CANDIDATE_PAIRS}"
echo "MIS_PATH5_MAX_INTRA_PER_CATEGORY: ${MIS_PATH5_MAX_INTRA_PER_CATEGORY}"
echo "MIS_PATH5_MAX_CROSS_PER_COMBO: ${MIS_PATH5_MAX_CROSS_PER_COMBO}"
echo "MIS_PATH5_MAX_CROSS_SOURCE_PER_CATEGORY: ${MIS_PATH5_MAX_CROSS_SOURCE_PER_CATEGORY}"
echo "MIS_PATH5_MAX_UNCATEGORIZED_MIX: ${MIS_PATH5_MAX_UNCATEGORIZED_MIX}"
echo "MIS_RETRIEVAL_WORKERS_PER_GPU: ${MIS_RETRIEVAL_WORKERS_PER_GPU}"
echo "MIS_PATH5_CRAWL_WORKERS: ${MIS_PATH5_CRAWL_WORKERS}"
echo "PEXELS_API_KEY: ${PEXELS_API_KEY:+<set>}"
echo "PIXABAY_API_KEY: ${PIXABAY_API_KEY:+<set>}"
echo "Log file: ${LOG_FILE}"

clean_flag=()
[[ "$CLEAN" == "1" ]] && clean_flag=("--clean")

python "$PROJECT_ROOT/run_path5.py" "${clean_flag[@]}" 2>&1 | tee "$LOG_FILE"
