#!/bin/bash
set -euo pipefail

PROJECT_ROOT="/mnt/hdd/xuran/multi_image_safety"
LOG_DIR="$PROJECT_ROOT/logs"
TIMESTAMP="$(date '+%Y%m%d_%H%M%S')"
LOG_FILE="$LOG_DIR/path6_${TIMESTAMP}.log"

mkdir -p "$LOG_DIR"

# shellcheck disable=SC1091
source "$PROJECT_ROOT/scripts/_load_local_env.sh"

export HF_HOME="${HF_HOME:-/mnt2/xuran_hdd/cache}"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
export VLLM_ENABLE_V1_MULTIPROCESSING="${VLLM_ENABLE_V1_MULTIPROCESSING:-0}"
export VLLM_WORKER_MULTIPROC_METHOD="${VLLM_WORKER_MULTIPROC_METHOD:-spawn}"
export MIS_PATH6_MAX_MODEL_LEN="${MIS_PATH6_MAX_MODEL_LEN:-8192}"
export MIS_PATH6_GPU_MEMORY_UTILIZATION="${MIS_PATH6_GPU_MEMORY_UTILIZATION:-0.68}"
export PYTHONPATH="$PROJECT_ROOT${PYTHONPATH:+:$PYTHONPATH}"
export MIS_RETRIEVAL_QUERY_MODE=adaptive
export MIS_RETRIEVAL_QUERY_VARIANTS=4
export MIS_RETRIEVAL_MAX_QUERY_WORDS="${MIS_RETRIEVAL_MAX_QUERY_WORDS:-3}"
export MIS_RETRIEVAL_CLIP_TOP_K="${MIS_RETRIEVAL_CLIP_TOP_K:-8}"
export MIS_RETRIEVAL_CLIP_KEEP="${MIS_RETRIEVAL_CLIP_KEEP:-2}"
export MIS_RETRIEVAL_CLIP_MIN_SCORE_LOCAL="${MIS_RETRIEVAL_CLIP_MIN_SCORE_LOCAL:-0.20}"
export MIS_RETRIEVAL_CLIP_MIN_SCORE_WEB="${MIS_RETRIEVAL_CLIP_MIN_SCORE_WEB:-0.22}"
export MIS_LOCAL_SEARCH_MODE="${MIS_LOCAL_SEARCH_MODE:-thorough}"
export MIS_LOCAL_SOURCE_MIX="${MIS_LOCAL_SOURCE_MIX:-1}"
export MIS_LOCAL_SEARCH_EARLY_STOP_AT="${MIS_LOCAL_SEARCH_EARLY_STOP_AT:-8}"
export MIS_LOCAL_SEARCH_TARGET_CANDIDATES="${MIS_LOCAL_SEARCH_TARGET_CANDIDATES:-10}"
export MIS_RECAP_QUERY_LIMIT="${MIS_RECAP_QUERY_LIMIT:-96}"
export MIS_SINGLE_IMAGE_LOCAL_CANDIDATES="${MIS_SINGLE_IMAGE_LOCAL_CANDIDATES:-12}"
export MIS_RETRIEVAL_ALLOW_COMPACT_REWRITE="${MIS_RETRIEVAL_ALLOW_COMPACT_REWRITE:-1}"
export MIS_PATH6_CHAINS_PER_CATEGORY="${MIS_PATH6_CHAINS_PER_CATEGORY:-15}"
export MIS_PATH6_CHAIN_ROUNDS="${MIS_PATH6_CHAIN_ROUNDS:-50}"
export MIS_PATH6_THETA_HARM="${MIS_PATH6_THETA_HARM:-0.20}"
export MIS_PATH6_MIN_PASS_RATE="${MIS_PATH6_MIN_PASS_RATE:-0.02}"
export MIS_PATH6_FALLBACK_TOP_K="${MIS_PATH6_FALLBACK_TOP_K:-12000}"
export MIS_PATH6_FUSION_TARGET_PAIRS="${MIS_PATH6_FUSION_TARGET_PAIRS:-5500}"
export MIS_RETRIEVAL_WORKERS_PER_GPU="${MIS_RETRIEVAL_WORKERS_PER_GPU:-8}"
export MIS_PATH5_CRAWL_WORKERS="${MIS_PATH5_CRAWL_WORKERS:-12}"
export MIS_PATH6_ALLOW_IMAGE_GENERATION=1
export MIS_PATH6_SKIP_LOCAL_DATASETS="${MIS_PATH6_SKIP_LOCAL_DATASETS:-0}"

# ── 是否清除 step 完成标记，重新增量运行 ──────────────────────────────────────
# 修改这里：1 = 清除标记（增量重跑所有步骤），0 = 跳过已完成步骤
# Path 6 需全量重跑以生成 3000 samples，设为 1
CLEAN=1

# 也可以在命令行传 --clean 覆盖此设置
for arg in "$@"; do
  [[ "$arg" == "--clean" ]] && CLEAN=1
done

echo "Running Path 6: TAG+KG Fusion"
echo "CUDA_VISIBLE_DEVICES: ${CUDA_VISIBLE_DEVICES:-<not set>}"
echo "MIS_GPU_CANDIDATES: ${MIS_GPU_CANDIDATES:-<not set>}"
echo "MIS_PATH6_ALLOW_IMAGE_GENERATION: ${MIS_PATH6_ALLOW_IMAGE_GENERATION}"
echo "MIS_RETRIEVAL_MAX_QUERY_WORDS: ${MIS_RETRIEVAL_MAX_QUERY_WORDS}"
echo "MIS_LOCAL_SEARCH_MODE: ${MIS_LOCAL_SEARCH_MODE}"
echo "MIS_LOCAL_SOURCE_MIX: ${MIS_LOCAL_SOURCE_MIX}"
echo "MIS_LOCAL_SEARCH_EARLY_STOP_AT: ${MIS_LOCAL_SEARCH_EARLY_STOP_AT}"
echo "MIS_LOCAL_SEARCH_TARGET_CANDIDATES: ${MIS_LOCAL_SEARCH_TARGET_CANDIDATES}"
echo "MIS_SINGLE_IMAGE_LOCAL_CANDIDATES: ${MIS_SINGLE_IMAGE_LOCAL_CANDIDATES}"
echo "MIS_RECAP_QUERY_LIMIT: ${MIS_RECAP_QUERY_LIMIT}"
echo "MIS_RETRIEVAL_ALLOW_COMPACT_REWRITE: ${MIS_RETRIEVAL_ALLOW_COMPACT_REWRITE}"
echo "MIS_PATH6_CHAINS_PER_CATEGORY: ${MIS_PATH6_CHAINS_PER_CATEGORY}"
echo "MIS_PATH6_CHAIN_ROUNDS: ${MIS_PATH6_CHAIN_ROUNDS}"
echo "MIS_PATH6_THETA_HARM: ${MIS_PATH6_THETA_HARM}"
echo "MIS_PATH6_MIN_PASS_RATE: ${MIS_PATH6_MIN_PASS_RATE}"
echo "MIS_PATH6_FALLBACK_TOP_K: ${MIS_PATH6_FALLBACK_TOP_K}"
echo "MIS_PATH6_FUSION_TARGET_PAIRS: ${MIS_PATH6_FUSION_TARGET_PAIRS}"
echo "MIS_RETRIEVAL_WORKERS_PER_GPU: ${MIS_RETRIEVAL_WORKERS_PER_GPU}"
echo "MIS_PATH5_CRAWL_WORKERS: ${MIS_PATH5_CRAWL_WORKERS}"
echo "MIS_PATH6_SKIP_LOCAL_DATASETS: ${MIS_PATH6_SKIP_LOCAL_DATASETS}"
echo "PEXELS_API_KEY: ${PEXELS_API_KEY:+<set>}"
echo "PIXABAY_API_KEY: ${PIXABAY_API_KEY:+<set>}"
echo "Log file: ${LOG_FILE}"

clean_flag=()
[[ "$CLEAN" == "1" ]] && clean_flag=("--clean")

python "$PROJECT_ROOT/run_path6.py" "${clean_flag[@]}" 2>&1 | tee "$LOG_FILE"
